# branches to build
branches:
  # whitelist
  only:
    - master
    
image: Visual Studio 2019

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  disable_publish_on_pr: true

build_script:
- ps: .\src\Pdgt.BookApi\Build.ps1
